### ISSUE TITLE
Running a Second Node

### ISSUE THREAD

**Issue by kencarabello** [ewrogers/gala-docker#1]
Hey man.
Thanks for this great repo.
I'm pretty good with docker.
Only thing is. I'm getting stuck with the build command:
docker build -t gala-node:latest .
What I did was, I created 2 directories - one for each node.
but when I try to build node-2.
It's the same image in both nodes.
Is that ok?
How do I differentiate between the 2?
Would that be in the .configure?
If so, then I'm all good.
Please advise.
Thanks.
Ken

**Comment by ewrogers** [comment]
To run the second node you don't need to re-build a second container or even use another directory.

If the second node is on the same Gala account you just use the same `docker start` command but add `-e NODE_SPECIFIER=2`. You can verify that is working properly when you `docker attach` and see the `:2` at the end of the machine ID.

If the second node is on another Gala account, you should copy/modify the `.env` file as `second.env` (being sure to change credentials) and then use that for your `--envFile second.env` arg when starting the second node.

**Comment by kencarabello** [comment]
I don't know the syntax re: the -e NODE_SPECIFIER=2
Could you post an example of a full Node 2 start up syntax, 
where a Node 1 is hypothetically already running?
In other words, how do you alter this bit of code to include (specify)
the second node?:

$ docker run -itd --name "gala-node-1" \
  --restart=unless-stopped \
  --env-file .env \
  -v /etc/machine-id:/etc/machine-id \
  gala-node:latest

That would help.
Thanks.

**Comment by ewrogers** [comment]
```
$ docker run -itd --name "gala-node-2" -e NODE_SPECIFIER=2 --restart=unless-stopped --env-file .env -v /etc/machine-id:/etc/machine-id gala-node:latest
```

**Comment by kencarabello** [comment]
Great!
Thank you, Erik.
